List<Map<String, dynamic>> countries = [
  {
    "id": 1,
    "Country": "Germany",
    "Image": "assets/images/germanypic.jpg",
    "Description":
        "Germany, country of north-central Europe,traversing the continent’s main physical divisions, from the outer ranges of the Alps northward across the varied landscape of the Central German Uplands and then across the North German Plain.Germany One of Europe’s largest countries, Germany encompasses a wide variety of landscapes: the tall, sheer mountains of the south; the sandy, rolling plains of the north; the forested hills of the urbanized west; and the plains of the agricultural east. At the spiritual heart of the country is the magnificent east-central city of Berlin, which rose phoenixlike from the ashes of World War II and now, after decades of partition, is the capital of a reunified Germany, and the Rhine River, which flows northward from Switzerland and is celebrated in visual art, literature, folklore, and song. Along its banks and those of its principal tributaries—among them the Neckar, Main, Moselle, and Ruhr—stand hundreds of medieval castles, churches, picturesque villages, market towns, and centres of learning and culture, including Heidelberg, the site of one of Europe’s oldest universities (founded in 1386), and Mainz, historically one of Europe’s most important publishing centres. All are centrepieces of Germany's thriving tourist economy, which brings millions of visitors to the country each year, drawn by its natural beauty, history, culture, and cuisine (including its renowned wines and beers).",
    "Place to visit 1": "assets/images/germany.webp",
    "Place to visit 2": "assets/images/germany5.jpg",
    "Place to visit 3": "assets/images/germany78.jpg",
  },
  {
    "id": 2,
    "Country": "France",
    "Image": "assets/images/france pic.jpg",
    "Description":
        "Author Lisa Alexander spent two years living in Paris after college, enjoys returning to France as often as possible, and most recently visited France in March 2023.Take a dream vacation in a country that's full of dreamy destinations. Fairy-tale castles, storybook country villages, fashionable seaside resorts, snowcapped mountains, and of course Paris, the elegant City of Light.Begin with the Eiffel Tower, the modern emblem of France. Then discover famous masterpieces of art at the Louvre Museum. Spend a day pretending to be royalty at the elegant Palace of Versailles. Save time for leisurely gourmet meals. Traditional French gastronomy has been inscribed on the UNESCO list of Intangible Cultural Heritage.Each region of France boasts its own distinctive cuisine and culture. The coastal region of Brittany offers the old-world charm of quaint fishing villages and ancient seaports, while the French Alps boasts a hearty cuisine of cheese fondue and charcuterie served in cozy chalets near ski slopes.Every corner of the country has a certain magic. Discover the wonders of travelers' favorite places and learn about the best things to do with my list of the top attractions in France.",
    "Place to visit 1": "assets/images/france23.jpg",
    "Place to visit 2": "assets/images/france45.jpg",
    "Place to visit 3": "assets/images/france3456.jpg",
  },
  {
    "id": 3,
    "Country": "Italy",
    "Image": "assets/images/italy pic.jpg",
    "Description":
        "Italy (Italian: Italia [i'ta:lja]), officially the Italian Republic (Italian: Repubblica Italiana [re'pubblika ita'lja:na]), is a country in Southern[14][15][16] and Western[17][a] Europe. Located in the middle of the Mediterranean Sea, it consists of a peninsula delimited by the Alps and surrounded by several islands.[18] Italy shares land borders with France, Switzerland, Austria, Slovenia and the enclaved microstates of Vatican City and San Marino. It has a territorial exclave in Switzerland (Campione) and an archipelago in the African Plate (Pelagie Islands). Italy covers an area of 301,340 km2 (116,350 sq mi),[3] with a population of nearly 60 million;[19] it is the tenth-largest country by land area in the European continent and the third-most populous member state of the European Union. Its capital and largest city is Rome.The Italian peninsula was historically the native place and destination of numerous ancient peoples.[20] The Latin city of Rome in central Italy, founded as a Kingdom, became a Republic that conquered the Mediterranean world and ruled it for centuries as an Empire.[21][22] With the spread of Christianity, Rome became the seat of the Catholic Church and of the Papacy. During the Early Middle Ages, Italy experienced the fall of the Western Roman Empire and inward migration from Germanic tribes. By the 11th century, Italian city-states and maritime republics expanded, bringing renewed prosperity through commerce and laying the groundwork for modern capitalism.[23][24] The Italian Renaissance flourished in Florence during the 15th and 16th centuries and spread to the rest of Europe. Italian explorers also discovered new routes to the Far East and the New World, helping to usher in the European Age of Discovery. However, centuries of rivalry and infighting between the Italian city-states among other factors left the peninsula divided into numerous states until the late modern period.[25][26] During the 17th and 18th centuries, the Italian economic and commercial importance significantly waned.[27]",
    "Place to visit 1": "assets/images/italy45.jpg",
    "Place to visit 2": "assets/images/italy78.jpeg",
    "Place to visit 3": "assets/images/italy567.jpg"
  },
  {
    "id" : 4,
    "Country" : "Switzerland",
    "Image" :  "assets/images/switzerland image.jpg",
    "Description" : "Switzerland was formed in 1291 by an alliance of cantons against the Habsburg dynasty—the Confoederatio Helvetica (or Swiss Confederation), from which the abbreviation CH for Switzerland derives—though only in 1848, when a new constitution was adopted, was the present nation formed. Prior to 1848, internal conflict was quite common, but Switzerland has enjoyed relative domestic tranquility since the mid-19th century, and its organization has remained essentially the same: it is a union of more than 3,000 communes, or municipalities, situated in 26 cantons, 6 of which are traditionally referred to as demicantons (half cantons) but function as full cantons. Ordinary citizens are able to participate at every level of politics and regularly exercise their will in referenda and initiatives, through which Swiss citizens directly make numerous policy decisions at the national and subnational level. Two effects of this popular involvement are evident: Swiss taxes are rather low by European standards, because voters are able to review and approve a broad range of expenditures, and political decision making tends to be slow, because contending individual claims and opinions must be allowed to be expressed at every step.That high level of citizen involvement prompted the renowned 20th-century Swiss playwright and ironist Friedrich Dürrenmatt to allegorize Switzerland as a prison in which each Swiss citizen was at the same time prisoner and guard. Even so, the Swiss blend of federalism and direct democracy is unique in the world and is considered central to the country’s political and economic success. And Switzerland is indeed a major economic power, thanks to its long tradition of financial services and high-quality, specialized manufactures of items such as precision timepieces, optics, chemicals, and pharmaceuticals, as well as of specialty foodstuffs such as Emmentaler cheese and milk chocolate. Switzerland is regularly judged to have among the world's highest standards of living.",
    "Place to visit 1" :"assets/images/switz1.jpg",
    "Place to visit 2" :"assets/images/switz2.jpg",
    "Place to visit 3" :"assets/images/switz3.jpg",
   },
   {
    "id" : 5,
    "Country" : "India",
    "Image":"assets/images/india.png",
    "Description" : "India has a very ancient tradition of art, which has exchanged many influences with the rest of Eurasia, especially in the first millennium, when Buddhist art spread with Indian religions to Central, East and Southeast Asia, the last also greatly influenced by Hindu art.[383] Thousands of seals from the Indus Valley Civilization of the third millennium BCE have been found, usually carved with animals, but a few with human figures. The Pashupati seal, excavated in Mohenjo-daro, Pakistan, in 1928-29, is the best known.[384][385] After this there is a long period with virtually nothing surviving.[385][386] Almost all surviving ancient Indian art thereafter is in various forms of religious sculpture in durable materials, or coins. There was probably originally far more in wood, which is lost. In north India Mauryan art is the first imperial movement.[387][388][389] In the first millennium CE, Buddhist art spread with Indian religions to Central, East and Southeast Asia, the last also greatly influenced by Hindu art.[390] Over the following centuries a distinctly Indian style of sculpting the human figure developed, with less interest in articulating precise anatomy than ancient Greek sculpture but showing smoothly flowing forms expressing prana (breath or life-force).[391][392] This is often complicated by the need to give figures multiple arms or heads, or represent different genders on the left and right of figures, as with the Ardhanarishvara form of Shiva and Parvati.[393][394] Most of the earliest large sculpture is Buddhist, either excavated from Buddhist stupas such as Sanchi, Sarnath and Amaravati,[395] or is rock cut reliefs at sites such as Ajanta, Karla and Ellora. Hindu and Jain sites appear rather later.[396][397] In spite of this complex mixture of religious traditions, generally, the prevailing artistic style at any time and place has been shared by the major religious groups, and sculptors probably usually served all communities.[398] Gupta art, at its peak c.300 CE - c.500 CE, is often regarded as a classical period whose influence lingered for many centuries after; it saw a new dominance of Hindu sculpture, as at the Elephanta Caves.[399][400] Across the north, this became rather stiff and formulaic after c.800 CE, though rich with finely carved detail in the surrounds of statues.[401] But in the South, under the Pallava and Chola dynasties, sculpture in both stone and bronze had a sustained period of great achievement; the large bronzes with Shiva as Nataraja have become an iconic symbol of India.[402][403]",
    "Place to visit 1" :"assets/images/india3.jpg",
    "Place to visit 2" :"assets/images/india2.jpg",
    "Place to visit 3" :"assets/images/india5.jpg",
   },

];
